### ISSUE TITLE
🔨  SecurityConfig webSecurityCustomizer 이슈

### ISSUE THREAD

**Issue by choihuk** [tipi-tapi/ai-paint-today-BE#12]
```console
WARN 72047 --- [           main] o.s.s.c.a.web.builders.WebSecurity       : You are asking Spring Security to ignore Ant [pattern='/swagger-ui/**']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
```

webSecurityCustomizer를 사용하여 특정 url은 filter 인증 없이 요청 가능하도록 설정하려고 했으나 선호되지 않는 방법이라 하기에 HttpSecurity의 authorizeHttpRequests 메서드를 사용하여 지정한 url에 대해 permitAll을 적용했으나 작동하지 않습니다.

일단 warn만 뜨고 시스템은 정상적으로 돌아가기에 webSecurityCustomizer를 사용하여 구현했으나 이 문제는 해결해야 될 것 같습니다.

좋은 방법이 없을까요?

**Comment by akalswl14** [comment]
https://github.com/spring-projects/spring-security/issues/10938
위 이슈에서 관련 내용이 있어보이니, 참고 부탁드려요!

**Comment by akalswl14** [comment]
@choihuk 
이번에 코드리뷰하면서, Spring Security 마이그레이션 내용을 살펴보게되었습니다.
찾아보니, WebSecurityCustomizer 빈을 컨테이너에 등록하는 것으로 변경되었다가, 스프링 시큐리티 6부터는 아예 '4'에서 보던 HttpSecurity쪽에 등록하는 것으로 변경되었다고 하는데요.
저희는 Spring Security 5.7.8을 사용하고 있더라구요. 이 부분에 이슈가 있는건 아닐까요?

**Comment by choihuk** [comment]
@akalswl14 
네 위에 링크의 설명을 찾아보면 web.ignore은 해당 엔드포인트에 대해 Spring Security가 보안 헤더나 기타 보호 조치를 제공하지 않음을 의미하기에 사용을 자제하라는 측면에서 경고를 날리는 것 같습니다. 실제로 디버깅해보니 해당 엔드포인트에 따라 필터가 적용하지 않는 것을 볼 수 있었습니다. 
그렇기에 HttpSecurity authorizeHttpRequests의 permitAll을 사용하여 필터는 적용하되, 권한 인증을 수행하지 않도록 하여 보안을 무시하지 않도록 설정하라는 의미인 것 같습니다.

그러나 저희는 permitAll 메서드가 적용되지 않은 이슈가 발생했는데 그 이유는 JwtAuthenticationFilter가 OncePerRequestFilter를 상속하기 때문입니다. OncePerRequestFilter는 모든 요청에 대해 한 번의 실행을 보장하는 필터로 authorizeRequests 설정과는 무관하게 실행됩니다. 

이를 해결하기 위해 OncePerRequestFilter가 제공하는 shouldNotFilter 메서드를 상속하여 특정 엔드포인트에 따라 해당 필터의 수행을 막으면 될 것 같습니다. 혹시 이 방안에 대해 어떻게 생각하시나요?

**Comment by choihuk** [comment]
이슈 해결했으니 닫겠습니다!
