### ISSUE TITLE
⚒️  OAuthProperties 기능 개선 방향 논의

### ISSUE THREAD

**Issue by choihuk** [tipi-tapi/ai-paint-today-BE#13]
pr #9
## Issue1
common/security/oauth2/entity 패키지의 GoogleProperties, AppleProperties는 application-oauth.yml 파일에서 clientId, clientSecret 속성값을 가져와 저장하는 클래스이다.

해당 클래스를 생성한 이유는 OAuthService에서 소셜 properties를 가져올 때 필드로 각각의 속성들을 가져오는 것이 아닌, OAuthProperties가 가져온 정보를 사용하는 측면이 가독성이 좋고, 책임을 분리하는 방법이라 생각했기 때문이다. 
또한 가장 큰 이유는 이 클래스를 구현할 당시 apple 소셜로그인의 정책 방향이 안드로이드와 ios 둘 다 구현하기로 정했기에 많은 속성값을 가져올 것을 예상하여 따로 관리하는 측면이 나을 것 같았다.

하지만 apple 소셜로그인을 ios만 구현하기로 정책을 수정했기에, 속성 값은 두 개밖에 안 나온다. 그렇다면 굳이 OAuthProperties를 만들 필요가 있을까요?

## Issue2
apple secret key는 유효기간을 30일보다 길게 잡을 수 없기에 30일이 지나기 전에 속성값을 변경해야 한다. 그렇다고 yml 파일에 secret key를 저장하지 말고 매 호출마다 secret key를 새로 만들기에는 아래와 같은 이유로 꺼려진다.

1. auth key를 안전한 곳에 저장하여 secret key를 만들 때마다 읽어와 암호화할 때 사용해야 한다.
2. 30일까지 보장하는 key를 매번 만드는 것 자체가 비효율적이라 생각한다.
3. secret key를 만들기 위해 많은 propreties들이 필요하다.(만약 구현하게 된다면 AppleProperties 클래스가 꼭 필요할 것이다)

다른 더 좋은 방법은 없을까요?

**Comment by akalswl14** [comment]
우선, apple secret key와 함께 만료일자를 함께 property 값을 가지도록 만들어, 요청시 마다의 별도의 복호화없이 만료일자로 만료 여부를 판단하여 apple secret key를 생성하도록 논의하였습니다.
따라서, GoogleProperties, AppleProperties도 별도의 클래스로 분리해야합니다. ( issue1)

추후, Redis를 도입해서, apple secret key와 만료일자를 메모리가 아닌 별도의 DB에 보관하도록 개선이 필요합니다.
