### ISSUE TITLE
⚒️ 글로벌 지원을 위한 타임존 도입

### ISSUE THREAD

**Issue by choihuk** [tipi-tapi/ai-paint-today-BE#162]
### 현재 타임존 정책은 다음과 같습니다.
- ec2, mysql 서버 타임존을 KST로 설정
- 모든 시각은 KST를 기준으로 저장하거나 구분함
- 프론트에서 넘어오는 모든 시각은 한국 시각으로 간주함

### 해당 정책대로 글로벌 지원을 도입하게 된다면 다음과 같은 문제점이 발생할 수 있습니다.
- 프론트에서 넘어오는 시각은 어떤 타임존이 적용된 시각인지 판단할 수 없기에 무조건 KST 시각이라는 가정으로 판단함
- 프론트로 시간 정보를 응답할 때 한국 시각을 기준으로 전달하기에 해외 유저의 비정상적인 동작이 예상됨

### 따라서 아래 작업이 필요합니다.
- 프론트로부터 로컬 타임존 정보를 포함한 시각을 받는다 (`1969-07-20T20:18:04.000Z`과 같이 오프셋으로 타임존 정보를 받는다)
  - 타임존 정보를 같이 받는 이유는 유저의 타임존에 따라 하루가 지났는지, 지나지 않았는지의 여부를 판단하는 등의 경우가 있기 때문입니다.
- 서버에 타임존 정보를 저장할지, 저장하지 않을지 여부
  - 서버에 타임존 정보 저장에 대한 판단은 서버에 저장된 시각을 조회할 때 저장된 타임존 정보를 사용할 경우가 있는지의 여부와 같습니다.
  - 다만, 저희 서비스에서 db에 저장된 시각의 타임존 정보를 사용할 경우는 떠오르지 않기에 굳이 서버에 타임존 정보를 저장할 필요가 없어보입니다.
  - 서버에 타임존 정보를 저장하지 않는다면 서버 시간을 타임존으로 통일해서 저장해야 할 것입니다.

### ToDo 정리 (각 작업시 이슈를 등록하여 진행하면 좋을 거 같습니다)

- [ ] ~~#163~~
- [ ] ~~db에 한국 시각으로 저장된 모든 값을 UTC 값으로 변환 (DATETIME 데이터 타입은 mysql 서버 타임존에 영향을 안 받기 때문에 수동으로 변환해야 함)~~
- [ ] ~~#165~~
- [ ] ~~#167~~
- [ ] ~~#169~~
- [ ] ~~#170~~
- [ ] ~~#171~~
- [ ] ~~#172~~
- [x] #173
- [ ] 일기 limit api에서 타임존 정보를 받아 일기 limit 검증

**Comment by nero-angela** [comment]
업데이트시 기존 App과 호환 여부도 같이 고민하면 좋을 듯~!
- 호환 가능하게 만들 수 있다면, 클라이언트에서 타임존 생략시 한국으로 취급하고 동일하게 동작하도록 만들기 등
- 호환이 불가능하다면, URL을 다르게 분기(API 버전을 추가한다던데 등)

**Comment by akalswl14** [comment]
> 프론트에서 넘어오는 시각은 어떤 타임존이 적용된 시각인지 판단할 수 없기에 무조건 KST 시각이라는 가정으로 판단함

그래서 API 쿼리 파라미터로 타임존을 받고, default는 utc+9(우리나라, 일본 시간)으로 잡으면 될 것 같다구 생각합니다~!
모든 API를 이렇게 처리할 수 있을 것 같은데, 불가능한 API가 있으면 공유해주세요!

**Comment by choihuk** [comment]
@nero-angela 
현재는 시각 response시 아래와 같은 형식입니다.
<img width="297" alt="image" src="https://github.com/tipi-tapi/ai-paint-today-BE/assets/39454230/49f2383e-7c90-4ac0-8327-bdb27b669041">
만약 **yyyy-mm-ddThh:mm:ss.SSS+hh:mm** 형태로 변경해서 response해도 기존 버전에 문제가 생기지는 않나요?

**Comment by akalswl14** [comment]
> 다만, 저희 서비스에서 db에 저장된 시각의 타임존 정보를 사용할 경우는 떠오르지 않기에 굳이 서버에 타임존 정보를 저장할 필요가 없어보입니다.
서버에 타임존 정보를 저장하지 않는다면 서버 시간을 타임존으로 통일해서 저장해야 할 것입니다.

저도 타임존을 저장할 필요는 없다고 생각합니다~ API에서 다 받기두 하구요. postgreSQL은 tz를 포함해서 저장할수있는데 조금 서운하네요🥲
todo에 달려 있는 것처럼 UTC로 통일하면 될 것 같습니다!

**Comment by nero-angela** [comment]
> @nero-angela 현재는 시각 response시 아래와 같은 형식입니다. <img alt="image" width="297" src="https://user-images.githubusercontent.com/39454230/258038119-49f2383e-7c90-4ac0-8327-bdb27b669041.png"> 만약 **yyyy-mm-ddThh:mm:ss.SSS+hh:mm** 형태로 변경해서 response해도 기존 버전이 정상적으로 동작할까요?

서버에서 받은 시간은 앱에서 다음 코드를 통해서 모두 local 시간으로 변경하고 있어요~!
```dart
DateTime.parse(iso8601String).toLocal()
```
제대로 변경되는지 여부는 [DartPad](https://dartpad.dev/?id=336843e0eb60ddd17cd70f519e2b16af)에서 확인해보실 수 있을 것 같아요~!

**Comment by choihuk** [comment]
오오 DartPad 신기하군요! response까지 기존 앱과 호환된다면 굳이 버전을 나누어 url을 만들지 않고 구현 가능해 보입니다!

**Comment by nero-angela** [comment]
개발을 거의 다 끝낸거로 알고있는데, 일기 date 시간에 타임존 적용시 발생할 것 같은 문제가 생각나서 일단 공유드려요. 🙏

## As Is
- v1 : KR기준으로 변환해서 모든 시간이 기록됨
- v2 : UTC 기준으로 변환해서 모든 시간을 기록하고, 유저가 요청하는 타임존에 맞춰서 데이터를 응답해줌

## Issue
- 달력 API : 유저의 타임존이 바뀌면, 하루의 기준이 바뀌기 때문에 특정 날짜에 일기가 2개 작성된 것으로 반환될 수 있음
- Front에선 일기가 여러개인 경우 첫 번째 일기반 보여주고 있기 때문에, 특정 일기가 안보이고 달력상 다음 날은 공백으로 보일 수 있음
<img width="552" alt="image" src="https://github.com/tipi-tapi/ai-paint-today-BE/assets/26322627/fbbc7420-5f61-4283-a0a3-825c078ebd13">

## To Be
- 1일 1일기 원칙이 지켜져야함

**Comment by choihuk** [comment]
확실히 일기 작성 시 유저 타임존에 따라 일기 생성 시각을 변환하여 저장하게 된다면 `타임존에 따라 일기 생성 시각`이 다르게 응답되기에 해당 이슈가 발생할 수 있을거 같습니다..!

저희가 타임존을 도입하려고 했던 이유를 생각해보면 서버 시간과 유저 시간이 다르기에 `서버 시간과 유저 시간을 동일하게 맞추기 위함`입니다.
하지만 지금 작업은 `모든 날짜 관련 api에 타임존을 적용`하려고 했기에 위와 같은 문제가 생겼다고 생각합니다.

따라서 지금까지 작업한 이슈들을 복기하면 다음과 같습니다.

- #163 일기 생성시 타임존과 상관없이 유저의 시각을 저장하므로 타임존에 따른 변환 과정이 없기에 굳이 서버 타임존을 UTC로 변경하지 않아도 될 것 같습니다.

- #165 일기 조회시 타임존과 관계없이 db에 저장된 일기 날짜를 그대로 반환합니다. 따라서 이전 로직을 그대로 사용하면 될 것 같습니다.
- #167 월별 일기 목록 조회 api도 유저 타임존에 따라 구간이 다른 것이 아닌 db에 저장된 월을 기준으로 조회하면 되기에 이전 로직을 그대로 사용하면 될 것 같습니다.
- #169 특정 날짜 일기 존재 여부 api 또한 유저 타임존과 상관없이 유저의 로컬 날짜에 해당하는 일기 존재 여부를 확인하면 되기에 이전 로직을 그대로 사용하면 될 것 같습니다.
- #170 마지막 일기 생성 시각 조회 api 또한 db에 저장된 일기 생성 시각을 타임존 정보 없이 그대로 반환하면 되기에 이전 로직 그대로 사용하면 될 것 같습니다.
- #171 일기 생성 api는 두 가지 이슈가 있습니다. 
  - 일기 생성시 일기 생성 시각은 프론트에서 보내준 날짜 + 서버 시각을 합쳐 db에 저장합니다. 다만 이 경우 서버 시각과 유저 시각이 다를 수 있기에 유저 시각을 프론트로부터 받아서 db에 저장해야 합니다. 따라서 프론트에서 날짜와 시각을 합쳐서 전달하면 서버는 데이터를 받아 추가 시각 조정 과정 없이 db에 저장해야 합니다.
 
  -  일기 생성 전 일기 limit 판단시 유저 시각을 기준으로 하루가 지났는지 판단해야 하기에 해당 이슈를 통해 구현한 새로운 로직을 적용해야 할 것 같습니다. 그 이유는 `유저의 시간에 따라 오늘 일기 작성 여부를 판단할 수 있기` 때문입니다. 하지만 서버는 어느 시간대의 유저가 요청한지 알 수 없기에 타임존을 받아야 합니다. 
- #172 일기 생성 가능 여부 조회 api는 일기 생성 api의 일기 limit 판단과 마찬가지로 유저 시간을 알아야 하기에 유저 타임존을 받아야 합니다. 다만 마지막 일기 작성 시간, 유효 리워드 생성일자 값에 타임존 정보를 넣을 필요는 없을거 같습니다.

**Comment by choihuk** [comment]
현재 열어둔 이슈는 전부 close하고 새롭게 작업할 이슈 등록 후 다시 진행하겠습니다~!

**Comment by akalswl14** [comment]
해당 이슈는 티켓 제도를 도입하며 타임존 정보를 받을 필요가 없어짐에 따라 close 하도록 하곘습니다 ! ( 티켓 제도를 도입하고 diaryDate로 검증하도록 로직을 변경하면서 글로벌 지원이 현재 반영되어있습니다. )
