### ISSUE TITLE
⚒️ 프로그라피 aws 지원 기간 종료에 따른 aws 인프라 마이그레이션

### ISSUE THREAD

**Issue by akalswl14** [tipi-tapi/ai-paint-today-BE#193]
프로그라피 8기의 aws 지원이 8월 26일까지로 종료됨에 따라, 미리 마이그레이션에 대비해야합니다.
테스트 서버는 프로그라피와 별도로 팀 프리티어를 사용하고 있으므로 무관합니다.

현재 프로그라피 aws 자원으로 ec2, rds, s3를 사용하고 있어 이에 마이그레이션이 필요해, 새로운 aws 계정을 생성해 프리티어에서 구성하고자 합니다.

다만, aws는 장기적으로는 프리티어 기간이 1년 뿐이므로 오라클과 같은 비교적 저렴하거나 무료이용 기간이 더 긴 클라우드 서비스를 이용하는 것이 좋습니다. 하지만, 해당 방안은 새로운 리소스를 적용하기 위한 러닝 커브 및 시간이 있기 때문에 26일 이내로 안정적으로 도입하기 어려운 상황이므로 현재는 새로운 aws 프리티어 계정을 이용하도록 논의하였습니다.

별도로, s3는 이용 비용이 비교적 비싼 편이고, 프리티어 한도가 금방초과될 수 있는 만큼 다른 리소스를 검토해야합니다.
회의 중에 제시된 해결방안으로는 cloudflare의 r2가 있습니다.

- [x] #195
- [x] #194
- [x] #198

**Comment by choihuk** [comment]
마이그레이션 완료했기에 해당 이슈는 닫겠습니다!
