### ISSUE TITLE
⚒️ 유저 그림 평가

### ISSUE THREAD

**Issue by choihuk** [tipi-tapi/ai-paint-today-BE#230]
- ~~유저 그림 평가(GOOD, BAD)~~
- 일기를 작성한 뒤 그림이 마음에 드는지 안 드는지 평가할 수 있음

유저 그림 평가시 GOOD, BAD의 평가 방식에서 1~5점 사이의 별점 평가로 바뀌었기에 수정하겠습니다.

~~또한 일기 상세 조회시 그림에 대한 평가도 같이 반환하도록 요청이 들어왔기에 따로 이슈를 파 변경하겠습니다!~~

일기 하나당 여러 개의 이미지를 작성할 수 있기에 각 이미지당 평가되도록 변경해야 합니다. 따라서 일기 테이블에 있는 평가를 이미지 테이블로 옮기겠습니다!

- [x] #243

**Comment by nero-angela** [comment]
일기 상세 조회시 나오는 그림들 평가 여부를 알 수 있을까요?

**Comment by choihuk** [comment]
> 일기 상세 조회 API에서 그림들 평가 여부를 알 수 있을까요?

@nero-angela 
**넵 일기 상세 조회 API에도 적용하겠습니다! **

- [ ] 일기 상세 조회시 그림들 평가 여부도 같이 반환되도록 변경
