### ISSUE TITLE
⚒️ S3의 이미지는 퍼블릭 액세스를 통해 접근하지 않고, Pre-Signed URL을 통해 접근할 수 있도록 수정

### ISSUE THREAD

**Issue by akalswl14** [tipi-tapi/ai-paint-today-BE#46]
현재 S3에 이미지를 업로드할 때, 'public-read'의 퍼블릭 액세스 읽기 권한을 부여합니다.
버킷에도 퍼블릭 액세스가 적용되어 있기 때문에 객체의 S3 URI를 안다면 언제나 접근할 수 있습니다.

아래의 목적을 위해 퍼블릭 접근을 막아야합니다.
1. 삭제가 되어도 S3 상에서는 이미지가 삭제되지 않으므로, 퍼블릭 액세스를 막아야한다.
2. 접근할 수 없는 이미지(소유가 아니거나,...)에 접근하지 않도록, 퍼블릭 액세스를 막아야한다.

따라서 퍼블릭 액세스를 막기 위해서는
1. S3 버킷의 퍼블릭 액세스 설정 해제
2. 이미지 업로드시 PRIVATE ACL 권한으로 설정하여 업로드
3. 이미지 조회를 위한 URL 리턴시, Pre-Signed URL로 발급하여 리턴

**Comment by choihuk** [comment]
퍼블릭 액세스한게 마음에 걸렸었는데 좋은 해결책인거 같습니다! 굳굳
